# Generated by Django 5.2.13 on 2026-09-30 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('trade', models.CharField(choices=[('contractor', 'Contractor'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('mason', 'Mason'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('cleaning', 'Cleaning crew'), ('technician', 'Appliance technician'), ('waterproofer', 'Waterproofing specialist'), ('designer', 'Interior designer')], db_index=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='providers/')),
                ('service_area', models.CharField(blank=True, help_text="e.g. 'Baneshwor, Kathmandu'.", max_length=120)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty when the provider quotes on request.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_unit', models.CharField(choices=[('fixed', 'Fixed price'), ('hour', 'Per hour'), ('day', 'Per day'), ('visit', 'Per visit'), ('sqft', 'Per sq. ft.'), ('piece', 'Per piece'), ('bag', 'Per bag'), ('kg', 'Per kg'), ('quote', 'On request')], default='quote', max_length=12)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text="Shows the 'Available today' badge.")),
                ('is_verified', models.BooleanField(default=False, help_text='Documents and references checked.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, help_text='Which catalog categories this provider is listed under.', related_name='providers', to='catalog.category')),
            ],
            options={
                'ordering': ['sort_order', '-rating', 'name'],
                'indexes': [models.Index(fields=['is_active', 'trade', 'sort_order'], name='providers_p_is_acti_e663ec_idx')],
            },
        ),
    ]
