# Generated by Django 5.2.13 on 2026-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='engagement',
            field=models.CharField(choices=[('in_house', 'Own crew'), ('partner', 'Partner')], db_index=True, default='partner', help_text='Partner unless they are on our own crew. Never shown to customers.', max_length=12),
        ),
    ]
