# Generated by Django 5.2.13 on 2026-10-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Link to their Facebook profile or page.'),
        ),
        migrations.AddField(
            model_name='provider',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='If different from the phone number above.', max_length=20),
        ),
    ]
