# Generated by Django 5.2.13 on 2026-10-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_facebook_url_provider_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The contractor this worker reports to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='providers.provider'),
        ),
    ]
