# Generated by Django 5.2.13 on 2026-09-22 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('project_type', models.CharField(blank=True, choices=[('residential', 'Residential building'), ('commercial', 'Commercial building'), ('renovation', 'Renovation / interiors'), ('consultancy', 'Design & consultancy only'), ('other', 'Other')], max_length=20)),
                ('budget', models.CharField(blank=True, max_length=60)),
                ('source', models.CharField(choices=[('website', 'Website'), ('app', 'Pakka Homes app'), ('phone', 'Phone'), ('other', 'Other')], db_index=True, default='website', max_length=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam')], db_index=True, default='new', max_length=12)),
                ('notes', models.TextField(blank=True, help_text='Internal only - not shown to the sender.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalog.subcategory')),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='enquiries_e_status_76dd9c_idx')],
            },
        ),
    ]
