# Generated by Django 5.2.13 on 2026-09-22 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vertical', models.CharField(choices=[('service', 'Service'), ('shop', 'Shop'), ('rental', 'Rental')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image_key', models.CharField(blank=True, help_text="Folder name of the bundled app asset, e.g. 'appliance-repair'.", max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/categories/')),
                ('icon', models.CharField(blank=True, help_text='Material icon name used by the app.', max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['vertical', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['vertical', 'is_active', 'sort_order'], name='catalog_cat_vertica_6fd50f_idx')],
                'constraints': [models.UniqueConstraint(fields=('vertical', 'slug'), name='uniq_category_vertical_slug'), models.UniqueConstraint(fields=('vertical', 'name'), name='uniq_category_vertical_name')],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty when the price is quoted on request.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_unit', models.CharField(choices=[('fixed', 'Fixed price'), ('hour', 'Per hour'), ('day', 'Per day'), ('visit', 'Per visit'), ('sqft', 'Per sq. ft.'), ('piece', 'Per piece'), ('bag', 'Per bag'), ('kg', 'Per kg'), ('quote', 'On request')], default='quote', max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/subcategories/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_popular', models.BooleanField(db_index=True, default=False, help_text="Surfaces in the app's 'Popular services' row.")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'ordering': ['category', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active', 'sort_order'], name='catalog_sub_categor_03be98_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='uniq_subcategory_category_slug')],
            },
        ),
    ]
