# Generated by Django 5.2.13 on 2026-09-30 11:48

import bookings.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=bookings.models.make_reference, editable=False, max_length=12, unique=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(db_index=True, max_length=32)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=160)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('slot', models.CharField(choices=[('morning', 'Morning (8am - 12pm)'), ('afternoon', 'Afternoon (12pm - 4pm)'), ('evening', 'Evening (4pm - 8pm)'), ('anytime', 'Anytime')], default='anytime', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('app', 'Pakka Homes app'), ('website', 'Website'), ('phone', 'Phone')], default='app', max_length=12)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal only - not shown to the customer.')),
                ('provider', models.ForeignKey(blank=True, help_text='Empty means the customer let us assign someone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='providers.provider')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catalog.subcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='bookings_bo_status_eb4fb1_idx'), models.Index(fields=['contact_phone', '-created_at'], name='bookings_bo_contact_7c800a_idx')],
            },
        ),
    ]
